### PR TITLE
Created ReplayEnterpriseStreamingEndpoint_v2.java

### PR DESCRIPTION
**Pull request by jakehschwartz**

### CODE REVIEW

**Comment by jimmoffitt** [comment]
Thanks, on my list to review!

**Comment by mamsanz** [comment]
Waiting eagerly for that class to be added! -_o

**Comment by jakehschwartz** [comment]
I actually have one more thing to add. The host name also needs to be added to the Constants class because it is different for replay. `gnip-stream.twitter.com` vs`gnip-stream.gnip.com`

**Comment by jakehschwartz** [comment]
Ok, now it has all the changes I've made. :)

**Comment by mamsanz** [comment]
Thank you both. I'm gonna put your code to good use.  : )

**Pull request merged**
